# Generated by Django 4.2.16 on 2026-04-02 16:06

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=100, verbose_name='apellido')),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='saldo de crédito')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='teléfono')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=10, verbose_name='estado')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='total')),
                ('credito_usado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='crédito usado')),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='monto pagado')),
                ('referencia_mp', models.CharField(blank=True, max_length=255, verbose_name='referencia MercadoPago')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordenes', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Orden',
                'verbose_name_plural': 'Órdenes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='nombre')),
                ('slug', models.SlugField(blank=True, max_length=250, unique=True, verbose_name='slug')),
                ('descripcion', models.TextField(blank=True, verbose_name='descripción')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio')),
                ('precio_original', models.DecimalField(decimal_places=2, help_text='Precio de referencia para mostrar tachado', max_digits=10, verbose_name='precio original')),
                ('talle', models.CharField(choices=[('0000', '0000'), ('000', '000'), ('00', '00'), ('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('12', '12'), ('14', '14')], max_length=4, verbose_name='talle')),
                ('genero', models.CharField(choices=[('nena', 'Nena'), ('nene', 'Nene'), ('unisex', 'Unisex')], max_length=7, verbose_name='género')),
                ('categoria', models.CharField(choices=[('remera', 'Remera'), ('pantalon', 'Pantalón'), ('vestido', 'Vestido'), ('campera', 'Campera'), ('mameluco', 'Mameluco'), ('conjunto', 'Conjunto'), ('calzado', 'Calzado'), ('accesorio', 'Accesorio')], max_length=10, verbose_name='categoría')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], default='disponible', max_length=10, verbose_name='estado')),
                ('historia', models.TextField(blank=True, help_text='Historia emocional de la prenda. Se muestra en el primer tercio del detalle.', verbose_name='historia de la prenda')),
                ('familia_origen', models.CharField(blank=True, help_text='Nombre o alias de la familia que entregó la prenda', max_length=200, verbose_name='familia de origen')),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de publicación')),
                ('revisado', models.BooleanField(default=False, verbose_name='revisado')),
                ('lavado', models.BooleanField(default=False, verbose_name='lavado')),
                ('sin_manchas', models.BooleanField(default=False, verbose_name='sin manchas')),
                ('es_destacado', models.BooleanField(default=False, help_text='Mostrar en la sección de destacados del Home', verbose_name='es destacado')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['-fecha_publicacion'],
            },
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productos', models.ManyToManyField(blank=True, related_name='wishlisted_by', to='core.producto', verbose_name='productos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Lista de deseos',
                'verbose_name_plural': 'Listas de deseos',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to=core.models.producto_image_path, verbose_name='imagen')),
                ('orden', models.IntegerField(default=0, verbose_name='orden')),
                ('es_principal', models.BooleanField(default=False, verbose_name='es imagen principal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Imagen de producto',
                'verbose_name_plural': 'Imágenes de producto',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='OrdenItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='precio unitario')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.orden', verbose_name='orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orden_items', to='core.producto', verbose_name='producto')),
            ],
            options={
                'verbose_name': 'Ítem de orden',
                'verbose_name_plural': 'Ítems de orden',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('tipo', models.CharField(choices=[('credito', 'Crédito'), ('debito', 'Débito')], max_length=10, verbose_name='tipo')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripción')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Transacción de crédito',
                'verbose_name_plural': 'Transacciones de crédito',
                'ordering': ['-fecha'],
            },
        ),
    ]
