# Generated by Django 4.2.16 on 2026-04-08 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orden',
            name='address_city',
            field=models.CharField(blank=True, max_length=100, verbose_name='ciudad'),
        ),
        migrations.AddField(
            model_name='orden',
            name='address_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='orden',
            name='address_province',
            field=models.CharField(blank=True, max_length=100, verbose_name='provincia'),
        ),
        migrations.AddField(
            model_name='orden',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='calle'),
        ),
        migrations.AddField(
            model_name='orden',
            name='address_zip',
            field=models.CharField(blank=True, max_length=10, verbose_name='código postal'),
        ),
        migrations.AddField(
            model_name='orden',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='costo de envío'),
        ),
        migrations.AddField(
            model_name='orden',
            name='shipping_type',
            field=models.CharField(choices=[('envio', 'Envío a domicilio'), ('retiro', 'Retiro en local')], default='retiro', max_length=10, verbose_name='tipo de entrega'),
        ),
        migrations.AlterField(
            model_name='orden',
            name='estado',
            field=models.CharField(choices=[('pending_payment', 'Pendiente de pago'), ('paid', 'Pagado'), ('shipped', 'Enviado'), ('ready_for_pickup', 'Listo para retirar'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], default='pending_payment', max_length=20, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='estado',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('pausado', 'Pausado'), ('vendido', 'Vendido'), ('reservado', 'Reservado')], default='disponible', max_length=10, verbose_name='estado'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(max_length=255, unique=True, verbose_name='ID de pago MercadoPago')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado'), ('in_process', 'En proceso'), ('cancelled', 'Cancelado'), ('refunded', 'Reembolsado')], default='pending', max_length=20, verbose_name='estado')),
                ('status_detail', models.CharField(blank=True, max_length=255, verbose_name='detalle del estado')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto')),
                ('payment_method', models.CharField(blank=True, max_length=50, verbose_name='método de pago')),
                ('payment_type', models.CharField(blank=True, max_length=50, verbose_name='tipo de pago')),
                ('installments', models.IntegerField(default=1, verbose_name='cuotas')),
                ('mp_response', models.JSONField(blank=True, default=dict, verbose_name='respuesta completa MP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='última actualización')),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.orden', verbose_name='orden')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-created_at'],
            },
        ),
    ]
