# Generated by Django 6.0.3 on 2026-04-08 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_orden_address_city_orden_address_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='eliminado',
            field=models.BooleanField(default=False, verbose_name='eliminado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_eliminacion',
            field=models.DateTimeField(blank=True, null=True, verbose_name='fecha de eliminación'),
        ),
        migrations.AddField(
            model_name='producto',
            name='monto_consignante',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cuánto dinero se le debe dar al que entregó la ropa', max_digits=10, verbose_name='monto a pagar al consignante'),
        ),
        migrations.AddField(
            model_name='producto',
            name='nota_consignante',
            field=models.CharField(blank=True, help_text='Quién entregó la ropa (uso interno admin)', max_length=200, verbose_name='nombre del consignante'),
        ),
    ]
