# Generated by Django 4.2.16 on 2026-04-11 00:47

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_consignment_softdelete_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=core.models.generate_credit_code, help_text='Código alfanumérico que el usuario ingresa para canjearlo', max_length=50, unique=True, verbose_name='código')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto de crédito')),
                ('max_usos', models.PositiveIntegerField(default=1, help_text='0 = sin límite de usos', verbose_name='máximo de usos')),
                ('usos_actuales', models.PositiveIntegerField(default=0, verbose_name='usos actuales')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripción')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación')),
                ('fecha_expiracion', models.DateTimeField(blank=True, help_text='Dejar vacío para que no expire', null=True, verbose_name='fecha de expiración')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='codigos_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
            ],
            options={
                'verbose_name': 'Código de crédito',
                'verbose_name_plural': 'Códigos de crédito',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='CreditCodeRedemption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='monto acreditado')),
                ('fecha', models.DateTimeField(auto_now_add=True, verbose_name='fecha de canje')),
                ('codigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes', to='core.creditcode', verbose_name='código')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canjes_credito', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Canje de código',
                'verbose_name_plural': 'Canjes de códigos',
                'ordering': ['-fecha'],
                'unique_together': {('codigo', 'usuario')},
            },
        ),
    ]
