# Generated by Django 4.2.16 on 2026-05-04 17:06

from django.db import migrations


TALLES = [
    ('0000', 0), ('000', 1), ('00', 2), ('0', 3),
    ('1', 4), ('2', 5), ('3', 6), ('4', 7), ('5', 8),
    ('6', 9), ('7', 10), ('8', 11), ('9', 12),
    ('10', 13), ('12', 14), ('14', 15),
]

CATEGORIAS = [
    'Remera', 'Pantalón', 'Vestido', 'Campera',
    'Mameluco', 'Conjunto', 'Calzado', 'Accesorio',
]


def populate(apps, schema_editor):
    Talle = apps.get_model('core', 'Talle')
    Categoria = apps.get_model('core', 'Categoria')
    from django.utils.text import slugify

    for nombre, orden in TALLES:
        Talle.objects.get_or_create(nombre=nombre, defaults={'orden': orden})

    for nombre in CATEGORIAS:
        Categoria.objects.get_or_create(nombre=nombre, defaults={'slug': slugify(nombre)})


def rollback(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_talle_categoria_models'),
    ]

    operations = [
        migrations.RunPython(populate, rollback),
    ]
