# Generated by Django 4.2.16 on 2026-05-04 17:21

from django.db import migrations


# Map old lowercase choice values → new Categoria.nombre (capitalized)
CATEGORIA_MAP = {
    'remera': 'Remera',
    'pantalon': 'Pantalón',
    'vestido': 'Vestido',
    'campera': 'Campera',
    'mameluco': 'Mameluco',
    'conjunto': 'Conjunto',
    'calzado': 'Calzado',
    'accesorio': 'Accesorio',
}


def normalize(apps, schema_editor):
    Producto = apps.get_model('core', 'Producto')
    for old, new in CATEGORIA_MAP.items():
        Producto.objects.filter(categoria=old).update(categoria=new)


def rollback(apps, schema_editor):
    Producto = apps.get_model('core', 'Producto')
    for old, new in CATEGORIA_MAP.items():
        Producto.objects.filter(categoria=new).update(categoria=old)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_populate_initial_talles_categorias'),
    ]

    operations = [
        migrations.RunPython(normalize, rollback),
    ]
