# Generated by Django 4.2.16 on 2026-05-05 23:19

from django.db import migrations


def set_site_domain(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.update_or_create(
        id=1,
        defaults={
            'domain': 'www.elroperitotienda.com.ar',
            'name': 'El Roperito',
        },
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_normalize_existing_product_talle_categoria'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.RunPython(set_site_domain, migrations.RunPython.noop),
    ]
